# Generated by Django 4.1.2 on 2023-05-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
