# Generated by Django 4.1.2 on 2023-07-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
