# Generated by Django 4.1.2 on 2023-07-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_description_useraccount_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='landscape_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
